### ISSUE TITLE
Null Safety?

### ISSUE THREAD

**Issue by mark8044** [edwardez/bbob_dart#1]
Any chance to upgrade this with Null Safety?  looks like a great repository and want to try it

**Comment by MartenM** [comment]
Created PR #2 for this.

**Comment by edwardez** [comment]
Null safety support is now published as https://pub.dev/packages/bbob_dart/versions/0.2.0-dev.1 
Thanks @MartenM !

**Comment by mark8044** [comment]
OUT FREAKING STANDING
